#import "syllabics.typ": roman, roman-to-syllabics, syllabics, syllabics-to-roman
#import "ipa.typ": ipa
#show raw.where(block: true): it => {
  set text(font: "Berkeley Mono", size: 1em)
  block(
    fill: luma(240),
    inset: 10pt,
    radius: 4pt,
    width: auto,
    it,
  )
}

#set text(font: "Charis", size: 11pt)
#show regex("[\u{1400}-\u{167F}]"): it => text(
  font: ("Noto Sans Canadian Aboriginal", "Euphemia UCAS"),
  it,
)
#align(center)[
  #text(size: 14pt, weight: "bold")[Phonokit — Inuktitut Syllabics (demo)]
  #v(0.3em)
  #text(size: 9pt, fill: gray)[
    Parallel text verified against #emph[Inuktitut Magazine] (Issue 133–134) #h(0.4em)·#h(0.4em)
    Tables need to be checked!
  ]
]

#v(1em)
#line(length: 100%)
#v(0.5em)

= Verified parallel text (Eastern dialect)

This is the opening of #emph[Qimugiuqsanirmut Sannginiqarniq] (Strength from the Sled) by Amber Aglukark, #emph[Inuktitut Magazine] Issue 133–134, p. 6. The Roman version is the magazine's own romanization; the syllabics column below is generated by `#syllabics(…)` and is character-for-character identical to the syllabics published in the magazine.


#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  row-gutter: 0.6em,
  [#text(weight: "bold", size: 10pt)[Roman (magazine)]],
  [#text(weight: "bold", size: 10pt)[Syllabics (`#syllabics(…)`)]],

  [
    #text(weight: "bold")[Qimugiuqsanirmut Sannginiqarniq]
  ],
  [
    #text(weight: "bold")[#syllabics("Qimugiuqsanirmut Sannginiqarniq")]
  ],

  [
    Angijualungmi nirutujumi nunaqaqtugut Nunavummi, tamanna nunanga
    isuqaqtujaarunniisuuq suurlu qaulluqtutitut titiraujarviksatitut
    matuingajuq, tamanna silaup kiglia ilagijauliqsuni tungujurnirmut,
    qaullurnirmullu akusimalutik, taimailingaliqattarmat qimuksiqsuni,
    tautuktarani, Inungnut piusirijauqattainnaqtumik
    atuqtauqattainnaqtumik atuliraangama.
  ],
  [
    #syllabics(
      "Angijualungmi nirutujumi nunaqaqtugut Nunavummi, tamanna nunanga isuqaqtujaarunniisuuq suurlu qaulluqtutitut titiraujarviksatitut matuingajuq, tamanna silaup kiglia ilagijauliqsuni tungujurnirmut, qaullurnirmullu akusimalutik, taimailingaliqattarmat qimuksiqsuni, tautuktarani, Inungnut piusirijauqattainnaqtumik atuqtauqattainnaqtumik atuliraangama.",
    )
  ],
)

